### PR TITLE
Add 3D object models: 1594, 1704, 1751, 3004

### PR DESCRIPTION
**Pull request by sl4shed**
Hello! In this pull request, I added 3D models for object id's:
 - 1594: Custom/Toggle orb
 - 1751: Magenta Dash orb
 - 1704: Green Dash orb
 - 3004: Spider orb

### CODE REVIEW

**Review by vianraaa — APPROVED** [review]
Models are of high quality, LGTM

**Comment by adafcaefc** [comment]
I don't think the models with current kA value will work, I will take a look and try to fix it

**Comment by adafcaefc** [comment]
image
image

The dash orbs seems to be flipped, I will try to fix this

**Comment by adafcaefc** [comment]
otherwise, good models, thanks for contributing!

**Comment by slashedCodes** [comment]
> image image
> 
> The dash orbs seems to be flipped, I will try to fix this

You dont need to, ill push a fix in a minute

**Comment by adafcaefc** [comment]
> > image image
> > The dash orbs seems to be flipped, I will try to fix this
> 
> You dont need to, ill push a fix in a minute

I fixed it already dw

**Comment by adafcaefc** [comment]
https://github.com/adafcaefc/Geome3Dash/releases/tag/develop

Once the mod is built (takes ~10 minutes) you can enjoy playing with your new models here

**Pull request merged**
